version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  flask-app:
    build: ./flask-app
    container_name: flask-app
    ports:
      - "5000:5000"
    networks:
      - app-network

  springboot-app:
    build: ./springboot-app
    container_name: springboot-app
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
