# Utilise une image de base officielle Ubuntu
FROM ubuntu:latest


RUN apt-get update && apt-get upgrade -y && apt-get install -y apache2 && apt-get install -y nano && apt-get install python && echo "<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Mon Service Web</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f7f7f7;
            color: #333;
            text-align: center;
            padding: 40px;
        }
        .container {
            background: white;
            padding: 30px;
            margin: auto;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
            max-width: 600px;
        }
        h1 {
            color: #007BFF;
        }
        p {
            font-size: 18px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Bienvenue sur mon service web</h1>
        <p>Ce service tourne dans un conteneur Docker avec Ubuntu et Apache.</p>
        <p>Il fait partie d'une architecture Docker composée d'Odoo, PostgreSQL et MySQL.</p>
        <p>Accédez à Odoo sur <a href="http://localhost:8069">localhost:8069</a>.</p>
    </div>
</body>
</html>
" > /var/www/html/index.html

 
CMD ["/bin/bash"]
